services:
  hugo:
    env_file: .env
    image: spielerei
    profiles: 
      - do-not-start
    build: 
      context: .
      args:
        - HUGO_VERSION
        - DART_SASS_VERSION
    working_dir: /go/src
    command: "sleep infinity"
    volumes:
      - .:/go/src

  nginx:
    image: nginx
    volumes:
      - ./public:/usr/share/nginx/html
    ports:
      - "8080:80"

