name: Deploy Hugo Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Test Go
        run: |
          go version

      # 1. Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      # 2. Installiere Hugo Extended
      - name: Install Hugo Extended
        run: |
          HUGO_VERSION="0.139.3" # Ersetze durch die gew端nschte Version
          curl -L "https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz" -o hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin/hugo
          hugo version

      - name: Update Hugo Modules
        run: hugo mod get -u

      - name: Get Paige
        run: hugo mod get -u github.com/willfaught/paige@v0.92.0
      
      - name: Vendor Hugo Modules
        run: hugo mod vendor

      - name: Debug Hugo Modules
        run: hugo mod graph

      # 4. Debugging: Pr端fe Dateien
      - name: Debug Shortcode Files
        run: find layouts/shortcodes -type f

      # 5. Website bauen
      - name: Build Hugo site
        run: hugo

      # 6. Deploy zur Webspace via SSH
      - name: Deploy to Webspace
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
          SERVER_PORT: ${{ secrets.PORT }}
          SERVER_USER: ${{ secrets.USER }}
          SERVER_HOST: ${{ secrets.SERVER_NAME }}
          SERVER_PATH: ${{ secrets.PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Server-Schl端ssel zu known_hosts hinzuf端gen
          ssh-keyscan -p "$SERVER_PORT" "$SERVER_HOST" >> ~/.ssh/known_hosts

          # Test SSH Connection
          ssh -v -p "$SERVER_PORT" "$SERVER_USER@$SERVER_HOST" echo "SSH connection successful"

          # Rsync mit sshpass
          rsync --progress -avz -e "ssh -p $SERVER_PORT" public/ "$SERVER_USER@$SERVER_HOST:$SERVER_PATH"