name: Deploy Hugo Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Environment
        run: |
          echo "OS Information:"
          uname -a
          echo "PATH:"
          echo $PATH
          echo "Available Binaries:"
          ls /usr/bin /bin

      - name: Test Go
        run: |
          go version

      # 1. Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Test Go
        run: |
          go version

      # 2. Installiere Hugo Extended
      - name: Install Hugo Extended
        run: |
          HUGO_VERSION="0.123.3" # Ersetze durch die gewünschte Version
          curl -L "https://github.com/gohugoio/hugo/releases/download/v$HUGO_VERSION/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz" -o hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin/hugo
          hugo version

      - name: Test Go
        run: |
          go version

      # 3. Update Hugo Modules
      - name: Update Hugo Modules
        run: hugo mod get -u

      # 3. Get paige
      - name: Get Paige
        run: hugo mod get -u github.com/willfaught/paige@v0.92.0
      

      - name: Vendor Hugo Modules
        run: hugo mod vendor

      - name: List all files
        run: find . -type f

      - name: Debug Hugo Modules
        run: hugo mod graph

      # 4. Debugging: Prüfe Dateien
      - name: Debug Shortcode Files
        run: find layouts/shortcodes -type f

      # 5. Website bauen
      - name: Build Hugo site
        run: hugo

      # 6. Deploy zur Webspace via SSH
      - name: Deploy to Webspace
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
          SSH_PASSWORD: ${{ secrets.SSH_KEY }}
          SERVER_PORT: ${{ secrets.PORT }}
          SERVER_USER: ${{ secrets.USER }}
          SERVER_HOST: ${{ secrets.SERVER_NAME }}
          SERVER_PATH: ${{ secrets.PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # SSH-Agent starten
          eval "$(ssh-agent -s)"

          # Private Key mit Kennwort hinzufügen
          echo "$SSH_PRIVATE_KEY" | ssh-add - <<< "$SSH_PASSWORD"

          # Server-Schlüssel zu known_hosts hinzufügen
          ssh-keyscan -p "$SERVER_PORT" "$SERVER_HOST" >> ~/.ssh/known_hosts

          # Teste die SSH-Verbindung
          ssh -p "$SERVER_PORT" "$SERVER_USER@$SERVER_HOST" echo "SSH connection successful"

          rsync -avz -e "ssh -i ~/.ssh/id_rsa -p $SERVER_PORT" $SERVER_PATH "$SERVER_USER@$SERVER_HOST:$SERVER_PATH"
