name: "Main / Deploy"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:

      - name: "Golang / Version"
        run: |
          go version

      - name: "Repo / Checkout"
        uses: actions/checkout@v3

      - name: "Sass / Install"
        run: sudo snap install dart-sass

      - name: "Hugo"
        uses: ./.github/actions/hugo
        with:
          hugo-version: 0.139.3

      - name: "Artifact / Upload"
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public
          if-no-files-found: error
          retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      
      - name: "Artfifact / Download"
        uses: actions/download-artifact@v4
        with:
          name: site
          path: public

      - name: "Deploy"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
          SERVER_PORT: ${{ secrets.PORT }}
          SERVER_USER: ${{ secrets.USER }}
          SERVER_HOST: ${{ secrets.SERVER_NAME }}
          SERVER_PATH: ${{ secrets.PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Server-Schlüssel zu known_hosts hinzufügen
          ssh-keyscan -p "$SERVER_PORT" "$SERVER_HOST" >> ~/.ssh/known_hosts

          # Test SSH Connection
          ssh -v -p "$SERVER_PORT" "$SERVER_USER@$SERVER_HOST" echo "SSH connection successful"

          # Rsync mit sshpass
          rsync --progress -avz -e "ssh -p $SERVER_PORT" public/ "$SERVER_USER@$SERVER_HOST:$SERVER_PATH"
