name: Deploy Hugo Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      # 2. Setup Hugo mit dem Actions-Modul
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Clear Hugo Module Cache
        run: rm -rf $HOME/.cache/hugo
      
      # 3. Update Hugo Modules
      - name: Update Hugo Modules
        run: hugo mod get -u

      # 3. Get paige
      - name: Get Paige
        run: hugo mod get -u github.com/willfaught/paige@v0.92.0
      

      - name: Vendor Hugo Modules
        run: hugo mod vendor

      # 8. Compile SCSS (optional)
      - name: Compile SCSS
        run: sass assets/css/paige/bootstrap/paige.scss:static/css/paige.css
      

      - name: List all files
        run: find . -type f

      - name: Debug Hugo Modules
        run: hugo mod graph

      # 4. Debugging: Prüfe Dateien
      - name: Debug Shortcode Files
        run: find layouts/shortcodes -type f

      # 5. Website bauen
      - name: Build Hugo site
        run: hugo

      # 6. Deploy zur Webspace via SSH
      - name: Deploy to Webspace
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -avz --delete public/ benutzername@dein-webspace.de:/path/to/your/website