name: "PR / Test"

on:
  push:
    branches:
      - feature/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Test Go
        run: |
          go version

      - name: "Repo / Checkout"
        uses: actions/checkout@v3

      - name: "Sass / Install"
        run: sudo snap install dart-sass

      - name: "Hugo"
        uses: ./.github/actions/hugo
        with:
          hugo-version: 0.139.3
      - uses: actions/upload-artifact@v4
        with:
          name: site
          path: public
          if-no-files-found: error
          retention-days: 7
