name: "Deploy a preview to github pages"

on:
  push:
    branches:
      - feature/update-layout

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:

      - name: "Golang / Version"
        run: |
          go version

      - name: "Repo / Checkout"
        uses: actions/checkout@v3

      - name: "Sass / Install"
        run: sudo snap install dart-sass

      - name: "Hugo"
        uses: ./.github/actions/hugo
        with:
          hugo-version: 0.139.3

      - name: "Artifact / Upload"
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: public
          if-no-files-found: error
          retention-days: 7

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  
          force_orphan: true     
          publish_branch: gh-pages 